php:
  image: php:7.4-apache
  container_name: xxx2
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./php:/var/www/html  
  links:
    - db

db:
  image: mysql:5.7
  container_name: yyy2
  environment:
      - MYSQL_ROOT_PASSWORD=root3
  ports:
    - "3307:3306"
  volumes:
    - ./mysql:/var/lib/mysql